class Course {
  final String titre;
  final String image;
  final String description;

  Course(this.titre, this.image, this.description);
}

List<Course> mobileCourses = [
  Course(
    "Flutter & Dart: Le Cours complet pour iOS et Android",
    "assets/course/flutter.jpg",
    "Connaissez vous Flutter? \n\nC'est le SDK (ou Kit de développement en français) de Google. Il permet de créer des applications à la fois pour Android et iOS. \n\nConnaissez vous Dart? \n\nC'est un langage de programmation orienté objet développé par Google. Il est facile à comprendre et à prendre en main et se rapproche de langages tels que Java ou Swift par exemple. \n\nDans ce cours nous allons ensemble apprendre à développer des applications à la fois pour iOS et Android avec Flutter et Dart. Nous partirons des bases pour créer au fil du cours des applications de plus en plus évoluées. \n\nPour bien mettre en pratique vos nouvelles compétences, vous aurez des challenges à faire tout au long du cours, comme par exemple créer une application de calcul de calories. \n\nVoici ce que vous allez apprendre durant ce cours: \n\nLa prise en main d'Android Studio, le logiciel qui vous servira durant votre apprentissage. \n\nLes bases de Dart. \n\nLa programmation orienté \n\nLes Widgets basiques \n\nCréation d'un lecteur audio \n\nLes Widgets Pop \n\nCréation d'un quizz \n\nLes Widgets Interactifs \n\nCréation d'un calculateur de calories \n\nAdapter les Widgets selon la plateforme(Android ou iOS) \n\nLes Listes \nLes Grilles \n\nCréation d'un Flux RSS \n\nLes Menus \nLa Geolocalisation \n\nUtiliser une API \n\nCréation d'une application météo. \n\nEt bien plus encore... \n\nAlors vous êtes prêts à vous lancer? Je vous attends dans le cours.",
  ),
  Course(
    "Créez des applications mobiles sans programmer + bonus",
    "assets/course/programmer+.jpg",
    "Aujourd’hui, tout le monde possède un smartphone. Toutes les grandes entreprises sont présentes sur les principaux magasins d’applications. Mais qu’en est-il des petites entreprises, des indépendants, des bloggeurs, des youtubeurs, des petits commerçants ? \n\nVous avez une chaîne Youtube, un podcast, un blog, un site de e-commerce, un restaurant, un commerce ? Vous aimeriez vous aussi rentrer dans le smartphone de vos clients, de vos prospects ? \n\nComment créer une application mobile pour votre chaîne Youtube, pour votre podcast, pour votre blog, pour votre site ? \n\nVous avez un commerce et vous aimeriez proposer à vos clients une carte de fidélité numérique ? Vous avez un gîte que vous souhaitez proposer à la location ? \n\nDevez-vous louer les services d’un développeur ? \n\nVous souhaitez développer vos activités de freelance, et proposer à vos clients la création d’une application mobile ? \n\nDevez-vous passer des mois, ou des années, à apprendre la programmation ? \n\nIl existe une solution qui vous évitera de dépenser des milliers d’euros ou des centaines d’heures de formation : utilisez un générateur d’applications mobiles ! \n\nEn moins d’une demi-journée, vous pourrez créer votre application mobile. C’est simple et amusant. Inutile d’apprendre la programmation. Vous pourrez même créer un nombre illimité d’applications mobiles. Vous pourrez utiliser le générateur d’applications mobiles, sans avoir d’abonnement à payer ! \n\nVous avez ici une opportunité unique : entrer sur le marché qui connaît la plus forte croissance au monde ! \n\nVous recevrez, en bonus, un compte (valable à vie) vous permettant de publier un nombre illimité d'applications ! \n\nAujourd'hui, grâce à cette formation, vous pouvez être présent vous aussi sur l’App Store, sur le Play Store, autrement dit sur le smartphone de milliers de personnes, vous pouvez créer votre activité de freelance dans ce secteur en plein essor. \n\nN’attendez pas, créez dès maintenant votre application mobile !",
  ),
  Course(
    "Les Progressive Web Apps (PWA) par la pratique",
    "assets/course/pwa.jpg",
    "Souvenez vous, il a bien longtemps, presque 15 ans, XMLHttpRequest évoluait dans l'indifférence générale, jusqu'à ce que par la magie du verbe - ou plutôt du nom, 'AJAX' - il devienne l'acteur principal du Web 2.0. Il est en train de se passer la même chose avec le service worker et les PWA. \n\nEn août 2015, Alex Russel a nommé les applications web qui recourent à un ensemble de technologies - service workers, cache, push notification ... - des Progressive Web Apps ou PWA. Cela a eu pour effet de les rendre plus visibles et plus populaires parmi les développeurs, particulièrement depuis la rentrée de septembre 2017. Exactement comme ça été le cas il y a plus 10 ans avec XMLHttpRequest et AJAX. \n\nAutrement dit, nous sommes à l'aube d'un tournant aussi majeur que l'a été AJAX. Ce qui revient à avoir en sa possession une boule de cristale qui nous annonce que les développeuses et développeurs qui sauront transformer des applications web classiques en PWA, ou directement créer des PWA, seront recherchés en 2018. \n\nC'est le moment idéal pour monter en compétence sur les diverses API qui utilisées ensemble, permettent d'améliorer vos applications web pour en faire des applications hybrides que vos utilisateurs installeront sur leurs smartphones.",
  ),
];

List<Course> langageCourses = [
  Course(
    "Devenez développeur Java",
    "assets/course/java.jpg",
    "Vous voulez devenir DÉVELOPPEUR JAVA et vous ne savez pas PAR QUOI COMMENCER ? \n\nVous êtes au bon endroit ! \n\nApprenez à programmer avec Java avec ce cours de référence : \n\nSimple, rapide, ludique et pratique avec de nombreux exercices auto-corrigés \n\nCouvre l'ensemble des concepts indispensable pour réaliser votre première application Java \n\nPrésenté par un professionnel et enseignant de près de 20 ans d'expérience \n\nVous serez guidé pas à pas sur le chemin de la réussite grâce à une progression pédagogique efficace. \n\nChaque chapitre traite d'un et un seul concept : un cours clair et précis \n\nChaque concept fait le plus souvent l'objet d'un atelier dédié : mettez vos nouvelles connaissances en pratique immédiatement ! \n\nInclut des tonnes de contenus additionnels ! \n\nAnimations \n\nVidéos YouTube \n\nDocuments et pages web complémentaires... \n\nFondé sur Java 8, il fait cependant l'économie des concepts complexes introduits dans cette version et non indispensable pour les débutants, comme la programmation fonctionnelle par exemple. L'intégralité du cours est compatible avec les versions ultérieures de Java, incluant Java 11 et 17. \n\nSuivez les 45 ateliers de l'application sur le thème de l'espace et de la conquête spatiale. \n\nLe cours s'inscrit dans un cursus complet de formation pour développeurs Java : \n\nDevenez développeur Java (ce cours) \n\nTravaux pratiques Java \n\nLibrairies Java et Intro Maven \n\nJava EE : Devenez développeur d'applications Web Java \n\nBien démarrer avec Spring et Spring Boot",
  ),
  Course(
    "Apprendre à programmer en C++ : Le guide de démarrage 2023",
    "assets/course/C++.jpg",
    "Si vous programmez déjà un peu en Python et que vous avez l'impression d'avoir fait le tour du langage mais qu'en même temps votre code vous semble complexe et peu optimisé, alors cette formation est faite pour vous. \n\nIl est possible de faire beaucoup avec des connaissances de base du langage, mais Python regorge de techniques avancées, parfois simples, parfois complexes, qui lorsque vous les connaissez, améliorent grandement la qualité de votre code. \n\nAu programme de cette formation : \n\nComprendre le fonctionnement des objets Python en mémoire, afin de pouvoir optimiser son code \n\nApprendre plusieurs fonctions qui vont vous permettre de réduire le nombre de lignes de code que vous aurez à écrire \n\nUtiliser l'introspection afin de pouvoir analyser votre code pour le déboguer et le comprendre en profondeur \n\nBien documenter votre code grâce aux docstrings \n\nVérifier des chaînes de caractère complexes grâce aux expressions régulières \n\nInstaller et gérer les modules Python sur notre machine grâce à PIP \n\nConnaître les 10 erreurs du débutant et savoir comment les éviter et y remédier \n\nOptimiser son code et aller plus vite grâce à plusieurs astuces qui rendront vos scripts bien plus efficaces et lisibles \n\nUtiliser les sets pour faire des opérations complexes sur plusieurs listes \n\nUtiliser les args et kwargs pour rendre vos fonctions versatiles et personnalisables \n\nCréer vos propres objets itérables grâces aux itérateurs et aux générateurs \n\nDans cette formation, je vous propose donc d'aller plus loin, de découvrir toutes ces petites astuces, ces fonctions avancées du langage et les erreurs à éviter, pour que votre code soit plus performant, plus solide et plus professionnel.",
  ),
  Course(
    "Python avancé : aller plus loin",
    "assets/course/python.jpg",
    "Si vous programmez déjà un peu en Python et que vous avez l'impression d'avoir fait le tour du langage mais qu'en même temps votre code vous semble complexe et peu optimisé, alors cette formation est faite pour vous. \n\nIl est possible de faire beaucoup avec des connaissances de base du langage, mais Python regorge de techniques avancées, parfois simples, parfois complexes, qui lorsque vous les connaissez, améliorent grandement la qualité de votre code. \n\nAu programme de cette formation : \n\nComprendre le fonctionnement des objets Python en mémoire, afin de pouvoir optimiser son code \n\nApprendre plusieurs fonctions qui vont vous permettre de réduire le nombre de lignes de code que vous aurez à écrire \n\nUtiliser l'introspection afin de pouvoir analyser votre code pour le déboguer et le comprendre en profondeur \n\nBien documenter votre code grâce aux docstrings \n\nVérifier des chaînes de caractère complexes grâce aux expressions régulières \n\nInstaller et gérer les modules Python sur notre machine grâce à PIP \n\nConnaître les 10 erreurs du débutant et savoir comment les éviter et y remédier \n\nOptimiser son code et aller plus vite grâce à plusieurs astuces qui rendront vos scripts bien plus efficaces et lisibles \n\nUtiliser les sets pour faire des opérations complexes sur plusieurs listes \n\nUtiliser les args et kwargs pour rendre vos fonctions versatiles et personnalisables \n\nCréer vos propres objets itérables grâces aux itérateurs et aux générateurs \n\nDans cette formation, je vous propose donc d'aller plus loin, de découvrir toutes ces petites astuces, ces fonctions avancées du langage et les erreurs à éviter, pour que votre code soit plus performant, plus solide et plus professionnel.",
  ),
];

// Add more courses




class CourseList {
  static List<Course> addedCourses = [];
}